config/routes.rb
ChecklistNew::Application.routes.draw do
  devise_for :admins
  devise_for :inspectors

  mount RailsAdmin::Engine => '/cms', :as => 'rails_admin'

  resources :lists do
    member do
      get "report"
    end
  end

  resources :lists do
    resources :reports, only: :index
  end

  resources :reports, only: :create

  root to: 'home#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  include Extensions::UUID

  devise :database_authenticatable, :trackable,  #, :registerable, :recoverable, :rememberable, :validatable
         :authentication_keys => [:login]

  attr_accessor :login

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :username, :login  #, :remember_me
  attr_accessible :list_ids
  #attr_accessible :title, :body
  has_many :lists

  protected
    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Extensions::UUID
  belongs_to :reports
  belongs_to :list_item
  belongs_to :inspector
  attr_accessible :value, :list_item_id, :inspector_id, :inspector, :list_item
end

app/models/extensions/uuid.rb
module Extensions
  module UUID
    extend ActiveSupport::Concern

    included do
      set_primary_key 'uuid'
      before_create :generate_uuid

      def generate_uuid
        self.id = UUIDTools::UUID.random_create.to_s
      end
    end
  end
end

app/models/inspector.rb
class Inspector < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  include Extensions::UUID
  devise :database_authenticatable, :trackable,  #, :registerable, :recoverable, :rememberable, :validatable
         :authentication_keys => [:login]

  attr_accessor :login

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :username, :login # , :remember_me

  # attr_accessible :title, :body
  has_many :reports
  has_many :answers, through: :reports

  protected
    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
end

app/models/list.rb
class List < ActiveRecord::Base
  include Extensions::UUID
  attr_accessible :description, :name
  attr_accessible :admin_id, :list_item_ids

  belongs_to :admin
  has_many :list_items
  has_many :reports

  accepts_nested_attributes_for :reports
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  include Extensions::UUID
  attr_accessible :description, :title, :answer_kind, :selection
  attr_accessible :list_id
  belongs_to :list
  serialize :selection

  def answer_kind_enum
    ['yes/no','longtext','selection', 'checkbox']
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  include Extensions::UUID
  belongs_to :inspector
  belongs_to :list
  has_many :answers
  attr_accessible :inspector, :inspector_id, :list, :list_id, :answers_attributes, :comment
  # attr_accessible :title, :body
  accepts_nested_attributes_for :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_inspector!
  before_filter :get_lists, only: [:index]
  before_filter :get_list, only: [:show, :edit, :update, :destroy, :report]
  respond_to :html, :json

  def index
    respond_with @lists
  end

  def new
    @list = List.new
    respond_with @list
  end

  def create
    @list = List.new params[:list]
    redirect_to lists_path if @list.save
  end

  def edit
    respond_with @list
  end

  def update
    redirect_to @list, notice: "List updated" if @list.save
  end

  def destroy
    redirect_to lists_path if @list.destroy
  end

  def report
    @report = @list.reports.build inspector: current_inspector
    for list_item in @list.list_items
      @report.answers.build list_item_id: list_item.id
    end
  end

  protected
    def get_list
      @list = List.includes(:list_items).find params[:id]
    end

    def get_lists
      @lists = List.all
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_inspector!
  before_filter :get_list_reports, only: [:index]

  def index
#    respond_with @reports
  end

  def create
    r = Report.new params[:report]
    r.inspector = current_inspector
    r.answers.each{|a| a.inspector = current_inspector}
#    redirect_to r.list, notice: "Report filed" if r.save
    redirect_to [r.list, :reports], notice: "Report filed" if r.save
  end

  protected
    def get_list_reports
      @list = List.find params[:list_id]
      @reports = @list.reports
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/answers/_answer.html.haml
- @answer ||= answer
- list_item = answer.list_item
.title= list_item.title
.description= list_item.description
.answers
  = render "answers/yesno" if list_item.answer_kind == "yes/no"
  = render "answers/selection" if list_item.answer_kind == "selection"
  = render "answers/longtext" if list_item.answer_kind == "longtext"
  = render "answers/checkbox" if list_item.answer_kind == "checkbox"

app/views/answers/_answer_fields.html.haml
- @answer = f.object
- list_item = @answer.list_item
.title= list_item.title
.description= list_item.description
.answers
  = render "answers/yesno", f: f if list_item.answer_kind == "yes/no"
  = render "answers/selection", f: f if list_item.answer_kind == "selection"
  = render "answers/longtext", f: f if list_item.answer_kind == "longtext"
  = render "answers/checkbox", f: f if list_item.answer_kind == "checkbox"

app/views/answers/_checkbox.html.haml
- for selection in @answer.list_item.selection
  %label
    = f.check_box "value", {:multiple => true}, selection, nil
    = selection

app/views/answers/_longtext.html.haml
= f.text_area "value"

app/views/answers/_selection.html.haml
- for selection in @answer.list_item.selection
  %label
    = f.radio_button "value", selection
    = selection

app/views/answers/_yesno.html.haml
%label
  = f.radio_button "value", "yes"
  Yes

%label
  = f.radio_button "value", "no"
  No

app/views/home/index.html.haml
%h1 Welcome!
%p #{link_to "Lists", lists_path}

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Checklist"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href= root_path ) Checklist
          .container.nav-collapse
            %ul.nav
              %li= link_to "List", lists_path
              /%li= link_to "Link 2", "/path2"
              /%li= link_to "Link 3", "/path3"

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "List", lists_path
              /%li= link_to "Link 2", "/path2"
              /%li= link_to "Link 3", "/path3"
        .span9
          = yield

      %footer
        %p &copy; Checklist 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/lists/_details.html.haml
%p
  %b Name:
  = @list.name
%p
  %b Description:
  = @list.description

app/views/lists/_form.html.haml
= form_for @list, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.number_field :user_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), lists_path, :class => 'btn'

app/views/lists/edit.html.haml
- model_class = List
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/lists/index.html.haml
- model_class = List
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @lists.each do |list|
      %tr
        %td= link_to list.id, list_path(list)
        %td= list.name
        %td= list.description
        %td=l list.created_at
        %td= link_to "Prepare new report", [:report, list]
        %td= link_to "View reports", [list, :reports]

app/views/lists/new.html.haml
- model_class = List
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/lists/report.html.haml
= render "details"
= form_for @report do |f|
  = f.hidden_field :list_id
  = f.fields_for :answers do |b|
    = render "answers/answer_fields", f: b
  = f.label :comment
  = f.text_field :comment
  %br
  = f.submit "Submit report"

app/views/lists/show.html.haml
- model_class = List
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @list.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @list.description
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @list.user_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), lists_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_list_path(@list), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), list_path(@list), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/reports/index.html.haml
- model_class = Report
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:created_at)
      %th= model_class.human_attribute_name(:comment)
      %th=#t '.actions', :default => t("helpers.actions")
  %tbody
    - @reports.each do |report|
      %tr
        %td= report.id  # link_to report.id, report
        %td= report.created_at
        %td= report.comment
        %td=# link_to "Prepare new report", [:report, list]